### ISSUE TITLE
Should hyphens be allowed in unquoted names?

### ISSUE THREAD

**Issue by danielaparker** [ietf-wg-jsonpath/draft-ietf-jsonpath-jsonpath#52]
The current draft allows hyphens in unquoted names appearing in path expressions. But should it?

Allowing hyphens leads to an issue with subtraction in filter expressions, see [Filter expression with subtraction](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_subtraction.html). Given

```
[{"key": 60}, {"key": 50}, {"key": 10}, {"key": -50}, {"key-50": -100}]
```
and selector
```
$[?(@.key-50==-100)]
```
it seems reasonable, consistent with the other arithmetic operations, to expect a result
```
[ { "key": -50  }]
```
11 of the implementations give this result, which includes all of the ones that use javascript as a script engine, and in particular Goessner.

However, if the identifier were determined to be `key-50`, then the result would be
```
{"key-50": -100}
```
13 of the implementations give this result.

More generally, should the draft allow unquoted names that would be illegal as identifiers in popular interpreters such as javascript?

**Comment by gregsdennis** [comment]
This is a duplicate of #16

**Comment by danielaparker** [comment]
> This is a duplicate of #16. I make the same argument and list language support for hyphens in identifiers.

My apologies! I overlooked that. I'll close this one, and make any further comments under that one.
